[package]
name = "mini_curl"
version = "0.1.0"
edition = "2024"

[dependencies]
reqwest = "0.11" # 使用最新稳定版本
tokio = { version = "1", features = ["full"] } # 如果需要异步支持
env_logger = "0.9" # 使用最新稳定版本，具体版本号可参考 crates.io


[dev-dependencies]
mockito = "0.25"